/**
 * GENERATED by scripts/sync-onboarding-flow.mjs. Do not edit by hand.
 * Mirror of the athlete apps' onboarding flow (src/flow/sections) so the funnel follows the live screens.
 * Sources: inkbound-web, inkbound-mobile.
 */
export interface FlowScreenDef {
  /** Screen id as emitted in product_events (onboarding_screen_view / onboarding_answer). */
  id: string;
  /** FLOW.md section number, 1 to 7. */
  section: number;
  /** Shown only for some answers, so fewer people reaching it is not a drop. */
  conditional: boolean;
}

export const FLOW_SCREEN_DEFS: FlowScreenDef[] = [
  { id: 's01_welcome', section: 1, conditional: false },
  { id: 's02_role', section: 1, conditional: false },
  { id: 's03_invite_parent', section: 1, conditional: true },
  { id: 's04_gender', section: 1, conditional: false },
  { id: 's05_feelings', section: 1, conditional: false },
  { id: 's06_feeling_normal', section: 1, conditional: false },
  { id: 's07_heard_from', section: 1, conditional: false },
  { id: 's08_worries', section: 1, conditional: false },
  { id: 's09_confidence', section: 1, conditional: false },
  { id: 's10_researched', section: 2, conditional: false },
  { id: 's11_target_list', section: 2, conditional: false },
  { id: 's12_emailed', section: 2, conditional: false },
  { id: 's13_replied', section: 2, conditional: true },
  { id: 's13b_replied_schools', section: 2, conditional: true },
  { id: 's14_video', section: 2, conditional: false },
  { id: 's15_offers', section: 2, conditional: false },
  { id: 's16_offer_schools', section: 2, conditional: true },
  { id: 's17_academics_transition', section: 3, conditional: false },
  { id: 's17b_school_type', section: 3, conditional: false },
  { id: 's18_school', section: 3, conditional: false },
  { id: 's19_grad_year', section: 3, conditional: true },
  { id: 's19_eligibility', section: 3, conditional: true },
  { id: 's19_transfer_reasons', section: 3, conditional: true },
  { id: 's19b_on_track', section: 3, conditional: true },
  { id: 's19c_moving_fast', section: 3, conditional: true },
  { id: 's19d_get_moving', section: 3, conditional: true },
  { id: 's20_gpa', section: 3, conditional: false },
  { id: 's21_tests', section: 3, conditional: true },
  { id: 's21b_scores', section: 3, conditional: true },
  { id: 's22_majors', section: 3, conditional: true },
  { id: 's22_majors_transfer', section: 3, conditional: true },
  { id: 's23_game_transition', section: 4, conditional: false },
  { id: 's24_club_team', section: 4, conditional: false },
  { id: 's25_league', section: 4, conditional: false },
  { id: 's25b_prep_school', section: 4, conditional: true },
  { id: 's25c_prep_also_club', section: 4, conditional: true },
  { id: 's25d_prep_club_details', section: 4, conditional: true },
  { id: 's26_pro_experience', section: 4, conditional: false },
  { id: 's27_position', section: 4, conditional: false },
  { id: 's28_athletics', section: 4, conditional: false },
  { id: 's29_stress_over', section: 5, conditional: false },
  { id: 's30_about_you', section: 5, conditional: false },
  { id: 's30b_create_account', section: 5, conditional: true },
  { id: 's31_verify_phone', section: 5, conditional: false },
  { id: 's32_find_home', section: 6, conditional: false },
  { id: 's33_goals', section: 6, conditional: false },
  { id: 's33b_invite_parent', section: 6, conditional: true },
  { id: 's34_building_plan', section: 6, conditional: false },
  { id: 's35_plan_ready', section: 6, conditional: false },
  { id: 's36_try_free', section: 7, conditional: false },
  { id: 's36b_trial_reminder', section: 7, conditional: false },
  { id: 's36c_who_pays', section: 7, conditional: true },
  { id: 's36d_parent_billing', section: 7, conditional: true },
  { id: 's37_paywall', section: 7, conditional: false },
  { id: 's37b_connecting', section: 7, conditional: true },
  { id: 's37c_spin_wheel', section: 7, conditional: true },
  { id: 's37d_parent_invite_sent', section: 7, conditional: true },
  { id: 's38_one_time_offer', section: 7, conditional: true },
];
